// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDh1F_QOdmObP8tbRRUHpPw9e5syjORaNY',
    appId: '1:366173587233:web:05e2ba13fb1426be9b2060',
    messagingSenderId: '366173587233',
    projectId: 'pingolearn-b5720',
    authDomain: 'pingolearn-b5720.firebaseapp.com',
    storageBucket: 'pingolearn-b5720.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv9COAMp8WAN3xCwWrsDydiukdiI0RUow',
    appId: '1:366173587233:android:225425f949fcc4db9b2060',
    messagingSenderId: '366173587233',
    projectId: 'pingolearn-b5720',
    storageBucket: 'pingolearn-b5720.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdn1CBy5owKJuteXs81wFm4STXbEh8MDI',
    appId: '1:366173587233:ios:998e38a04fb4ced39b2060',
    messagingSenderId: '366173587233',
    projectId: 'pingolearn-b5720',
    storageBucket: 'pingolearn-b5720.appspot.com',
    iosBundleId: 'com.example.eshopPingolearn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdn1CBy5owKJuteXs81wFm4STXbEh8MDI',
    appId: '1:366173587233:ios:998e38a04fb4ced39b2060',
    messagingSenderId: '366173587233',
    projectId: 'pingolearn-b5720',
    storageBucket: 'pingolearn-b5720.appspot.com',
    iosBundleId: 'com.example.eshopPingolearn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDh1F_QOdmObP8tbRRUHpPw9e5syjORaNY',
    appId: '1:366173587233:web:c86e31ef743423239b2060',
    messagingSenderId: '366173587233',
    projectId: 'pingolearn-b5720',
    authDomain: 'pingolearn-b5720.firebaseapp.com',
    storageBucket: 'pingolearn-b5720.appspot.com',
  );
}
